export enum ActionTypes {
  GET_EXCHANGE_RATES = "@@currency/GET_EXCHANGE_RATES",
  GET_EXCHANGE_RATES_SUCCESS = "@@currency/GET_EXCHANGE_RATES_SUCCESS",
  GET_EXCHANGE_RATES_ERROR = "@@currency/GET_EXCHANGE_RATES_ERROR",
}
